name: Coding Standard

on:
  # Run on all pushes and on all pull requests.
  push:
    branches:
      master
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  test:
    uses: "zetacomponents/.github/.github/workflows/coding-standard.yml@master"

